flags:
  text:
    integer-simple: false
  QuickCheck:
    base4point8: false
packages:
- '.'
extra-deps:
- GLURaw-1.4.0.2
- GLUT-2.5.1.1
- JuicyPixels-3.2.6.1
- MonadRandom-0.4
- OpenGL-2.9.2.0
- OpenGLRaw-1.5.0.1
- QuickCheck-2.8.1
- StateVar-1.1.0.1
- active-0.2.0.4
- adjunctions-4.2.1
- ansi-terminal-0.6.2.2
- ansi-wl-pprint-0.6.7.3
- async-2.0.2
- attoparsec-0.13.0.1
- base-orphans-0.4.4
- bifunctors-5
- bmp-1.2.5.2
- bytes-0.15.0.1
- cairo-0.12.5.3
- cereal-0.4.1.1
- circle-packing-0.1.0.4
- colour-2.3.3
- comonad-4.2.7.2
- contravariant-1.3.3
- data-default-0.5.3
- data-default-class-0.0.1
- data-default-instances-base-0.0.1
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- dequeue-0.1.12
- diagrams-cairo-1.3.0.3
- diagrams-contrib-1.3.0.5
- diagrams-core-1.3.0.2
- diagrams-lib-1.3.0.3
- diagrams-solve-0.1
- distributive-0.4.4
- dlist-0.7.1.2
- dual-tree-0.2.0.6
- exceptions-0.8.0.2
- fingertree-0.1.1.0
- force-layout-0.4.0.2
- free-4.12.1
- fsnotify-0.2.1
- gio-0.12.5.3
- glade-0.12.5.0
- glib-0.12.5.4
- gloss-1.9.2.1
- gloss-rendering-1.9.2.1
- groups-0.4.0.0
- gtk-0.12.5.7
- hashable-1.2.3.3
- hinotify-0.3.8.1
- intervals-0.7.1
- kan-extensions-4.2.2
- lens-4.12.3
- linear-1.19.1.3
- monoid-extras-0.4.0.1
- mtl-2.2.1
- nats-1
- newtype-0.2
- optparse-applicative-0.11.0.2
- pango-0.12.5.3
- parallel-3.2.0.6
- parsec-3.1.9
- prelude-extras-0.4
- primitive-0.6
- profunctors-5.1.1
- random-1.1
- reflection-2
- safe-0.3.9
- scientific-0.3.3.8
- semigroupoids-5.0.0.4
- semigroups-0.16.2.2
- split-0.2.2
- statestack-0.2.0.4
- stm-2.4.4
- tagged-0.8.1
- text-1.2.1.3
- tf-random-0.5
- transformers-compat-0.4.0.4
- unix-compat-0.4.1.4
- unordered-containers-0.2.5.1
- utf8-string-0.3.8
- vector-0.11.0.0
- void-0.7
- zlib-0.6.1.1
resolver: ghc-7.8
